site_name: analytix

plugins:
  - search
  - autorefs
  - mkdocstrings:
      # custom_templates: docs/templates
      handlers:
        python:
          options:
            # members_order: source
            # heading_level: 3
            docstring_style: numpy
            # docstring_section_style: list
            show_signature_annotations: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
  - include-markdown

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  # custom_dir: docs/overrides

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  font:
    text: Barlow
    code: JetBrains Mono

  logo: logo_white.png

  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/analytix/
      name: PyPI
    - icon: fontawesome/brands/github
      link: https://github.com/parafoxia/analytix
      name: Source

copyright: Copyright &copy; 2021-present Ethan Henderson

repo_name: parafoxia/analytix
repo_url: https://github.com/parafoxia/analytix

watch:
  - "analytix"

nav:
  - "index.md"
  - "Getting started":
    - "starting/installation.md"
    - "starting/googleapp.md"
    - "starting/firstapp.md"
  - "Guides":
    - "guides/troubleshooting.md"
    - "guides/dimensions.md"
    - "guides/filters.md"
    - "guides/metrics.md"
    - "guides/sort-options.md"
    - "guides/report-types.md"
    - "guides/new-playlist-reports.md"
    - "Migrating":
      - "guides/migrating/v5-v6.md"
      - "guides/migrating/v4-v5.md"
      - "guides/migrating/v3-v4.md"
  - "Reference":
    - "reference/client.md"
    - "reference/errors.md"
    - "reference/ux.md"
    - "reference/warnings.md"
    - "auth":
      - "reference/auth/flow.md"
      - "reference/auth/scopes.md"
      - "reference/auth/secrets.md"
      - "reference/auth/tokens.md"
      - "reference/auth/utils.md"
    - "groups":
      - "reference/groups/groups.md"
    - "reports":
      - "reference/reports/interfaces.md"
      - "reference/reports/resources.md"
