name: Check Dependencies

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  run-check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install deputil

      - name: Run check
        run: python -m deputil update requirements
