name: Check Support for Minimum Versions of Data Libraries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  run-check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8.18"

      - name: Install dependencies
        run: |
          python -m pip install openpyxl pandas==1.4 polars==0.15.17 pyarrow==5.0.0 pytest .

      - name: Run tests (pandas)
        run: python -m pytest tests/reports/test_interfaces.py -k to_pandas

      - name: Run tests (PyArrow)
        run: python -m pytest tests/reports/test_interfaces.py -k to_arrow

      - name: Run tests (Polars)
        run: python -m pytest tests/reports/test_interfaces.py -k to_polars
