name: Check Support for Minimum Versions of Data Libraries

on:
  schedule:
    - cron: "0 0 1,15 * *"

jobs:
  run-check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8.18"

      - name: Install dependencies
        run: |
          python -m pip install mock openpyxl pandas==0.23.2 polars==0.17.3 pyarrow==2.0.0 pytest .

      - name: Run tests (pandas)
        run: python -m pytest tests/reports/test_report_interfaces.py -k to_pandas

      - name: Run tests (PyArrow)
        run: python -m pytest tests/reports/test_report_interfaces.py -k to_arrow

      - name: Run tests (Polars)
        run: python -m pytest tests/reports/test_report_interfaces.py -k to_polars
