name: Publish Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements/docs.txt
      - run: pip install git+https://github.com/parafoxia/griffe@fix-warnings-section-admonition
      - run: mkdocs gh-deploy --force
